apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
- name: sonarqube
  version: "0.1.10"
  releaseName: sonarqube
  namespace: my-namespace
  valuesFile: values.yaml
  includeCRDs: false